AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/*.rb'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/StringLiterals:
  Enabled: false

Rails:
  Enabled: false