# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457c934abf62d7ecd23ef39d8553a078189690266caacf1b1030185d4ac588f4ca7ee8015c4a02a6548093ba19ec0a265882043dcf8ce4e86ad558a330a076a2
  facebook_app_id: 1344400962343487
  facebook_app_secret: 5effc735253c93c89ef1b674b72deee3
  twitter_app_id: W2slNQ0eDNmsHH7qyEgqJqLcz
  twitter_app_secret: IENNaSkWPLS4eLHZOswkoQgLXQYyGyFGCyUow2q1MMBittvEJL

test:
  secret_key_base: dffa3850bb8d434487755b47869d33b225ed811efd1bb2ad6d15b1722462b97c8c44998b53b8fdac10a9715139231b3b74ff2fe77fe1dfb66d4c71c4cd379f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
